dist: bionic
sudo: false
language: C
env:
    global:
        - DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
        - DESTDIR=dist
        - IPCALC=0.4.0
addons:
    apt:
        packages:
            - bash
            - wget
            - make
notifications:
    email: false
install:
    - wget -q https://gitlab.com/ipcalc/ipcalc/-/archive/$IPCALC/ipcalc-$IPCALC.tar.gz -O ipcalc-$IPCALC.tar.gz
    - tar xf ipcalc-$IPCALC.tar.gz
    - make -C ipcalc-$IPCALC USE_GEOIP=no USE_MAXMIND=no
    - cp ipcalc-$IPCALC/ipcalc .
    - rm -rf ipcalc-$IPCALC.tar.gz ipcalc-$IPCALC

script:
    - export PATH=$PWD:$PATH
    - rm -rf $DESTDIR
    - mkdir -p $DESTDIR
    - wget -q http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest -O $DESTDIR/delegated-apnic-latest
    - awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' < $DESTDIR/delegated-apnic-latest >$DESTDIR/chnroute.txt
    - awk -F\| '/CN\|ipv6/ { printf("%s/%d\n", $4, $5) }' < $DESTDIR/delegated-apnic-latest >$DESTDIR/chnroute6.txt
    - rm -f $DESTDIR/delegated-apnic-latest
    - ipmerge.sh $DESTDIR/chnroute.txt >$DESTDIR/chnroute-min.txt
    - ipmerge.sh $DESTDIR/chnroute6.txt >$DESTDIR/chnroute6-min.txt
    - echo "# Generated on $DATE_TIME" >$DESTDIR/index.md
    - echo '## [chnroute.txt](chnroute.txt)' >>$DESTDIR/index.md
    - echo '## [chnroute6.txt](chnroute6.txt)' >>$DESTDIR/index.md
    - echo '## [chnroute-min.txt](chnroute-min.txt)' >>$DESTDIR/index.md
    - echo '## [chnroute6-min.txt](chnroute6-min.txt)' >>$DESTDIR/index.md

deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: $DESTDIR
    keep_history: true
    edge: true
    skip_cleanup: true
    committer_from_gh: true
    commit_message: "Generated on $DATE_TIME"
    on:
        branch: master
